<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\PaycomEntraProvisioner.Core\PaycomEntraProvisioner.Core.csproj" />
    <ProjectReference Include="..\PaycomEntraProvisioner.Paycom\PaycomEntraProvisioner.Paycom.csproj" />
    <ProjectReference Include="..\PaycomEntraProvisioner.Graph\PaycomEntraProvisioner.Graph.csproj" />
    <ProjectReference Include="..\PaycomEntraProvisioner.Data\PaycomEntraProvisioner.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.14.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
